pipeline:
  build:
    image: node:6.9.5
    environment:
      - NPM_CONFIG_LOGLEVEL=warn
      - NODE_ENV=production
    commands:
      - npm install
      - scripts/build-frontend.sh
  push:
    image: plugins/docker
    registry: quay.io
    repo: quay.io/ktbartholomew/keithbartholomew.com
    secrets:
      - docker_username
      - docker_password
    tags:
      - "latest"
      - "${DRONE_COMMIT_SHA}"
    when:
      branch: master
      event: [push, tag, deployment]
  kube_deploy:
    image: gcr.io/google_containers/hyperkube:v1.7.5
    secrets:
      - kubeconfig
    commands:
      - echo "$KUBECONFIG" > /kubeconfig
      - kubectl --kubeconfig /kubeconfig -n keithbartholomew set image deployment/keithbartholomew keithbartholomew=quay.io/ktbartholomew/keithbartholomew.com:${DRONE_COMMIT_SHA} --record
      - kubectl --kubeconfig /kubeconfig -n keithbartholomew rollout status deployment/keithbartholomew
    when:
      branch: master
      event: [push, tag, deployment]
  kube_deploy_undo:
    image: gcr.io/google_containers/hyperkube:v1.7.5
    secrets:
      - kubeconfig
    commands:
      - echo "$KUBECONFIG" > /kubeconfig
      - kubectl --kubeconfig /kubeconfig -n keithbartholomew rollout undo deployment/keithbartholomew
    when:
      branch: master
      event: [push, tag, deployment]
      status: failure
  failure_notify:
    image: raarts/netutils
    commands:
      - env
      - echo $MAILGUN_DOMAIN
      - >
        curl -sv --user "api:$MAILGUN_APIKEY" -XPOST \
        https://api.mailgun.net/v3/$MAILGUN_DOMAIN/messages \
        -F "from=Drone <postmaster@$MAILGUN_DOMAIN>" \
        -F "to=$EMAIL_RECIPIENT" \
        -F "subject=WARNING: drone build failed" \
        -F "text=this is a test from drone. good luck!"
    secrets:
      - email_recipient
      - mailgun_apikey
      - mailgun_domain
    # when:
    #   branch: master
    #   event: [push, tag, deployment]
    #   status: failure
