pipeline:
  build:
    image: node:6.9.5
    environment:
      - NPM_CONFIG_LOGLEVEL=warn
      - NODE_ENV=production
    commands:
      - npm install
      - scripts/build-frontend.sh

  push:
    image: plugins/docker
    registry: quay.io
    username: ${QUAY_USERNAME}
    password: ${QUAY_PASSWORD}
    repo: quay.io/ktbartholomew/os
    tags: latest
    when:
      branch: master
      event: [push, tag, deployment]

  deploy:
    image: quay.io/ktbartholomew/kubectl:1.5.2
    environment:
      - KUBE_SERVER=${KUBE_SERVER}
      - KUBE_TOKEN=${KUBE_TOKEN}
      - KUBE_CA_DATA=${KUBE_CA_DATA}
    commands:
      - echo "${KUBE_CA_DATA}" | base64 -d > /tmp/kube-cluster.ca
      - alias kubectl="kubectl --server ${KUBE_SERVER} --certificate-authority /tmp/kube-cluster.ca --token ${KUBE_TOKEN}"
      - for f in manifests/*.yml; do scripts/template_manifest.sh $f | kubectl apply -f -; done
    when:
      branch: master
      event: [push, tag, deployment]
