pipeline:
  test:
    image: docker
    commands:
      - docker info
      - docker build -t quay.io/ktbartholomew/keithbartholomew.com:${DRONE_COMMIT_SHA} .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  push:
    image: plugins/docker
    registry: quay.io
    repo: quay.io/ktbartholomew/keithbartholomew.com
    secrets:
      - docker_username
      - docker_password
    tags:
      - "latest"
      - "${DRONE_COMMIT_SHA}"
    when:
      branch: master
      event: [push, tag, deployment]
  kube_deploy:
    image: gcr.io/google_containers/hyperkube:v1.7.5
    secrets:
      - kubeconfig
    commands:
      - echo "$KUBECONFIG" > /kubeconfig
      - kubectl --kubeconfig /kubeconfig -n keithbartholomew set image deployment/keithbartholomew keithbartholomew=quay.io/ktbartholomew/keithbartholomew.com:${DRONE_COMMIT_SHA} --record
      - kubectl --kubeconfig /kubeconfig -n keithbartholomew rollout status deployment/keithbartholomew
    when:
      branch: master
      event: [push, tag, deployment]
  kube_deploy_undo:
    image: gcr.io/google_containers/hyperkube:v1.7.5
    secrets:
      - kubeconfig
    commands:
      - echo "$KUBECONFIG" > /kubeconfig
      - kubectl --kubeconfig /kubeconfig -n keithbartholomew rollout undo deployment/keithbartholomew
    when:
      branch: master
      event: [push, tag, deployment]
      status: failure
  failure_notify:
    image: raarts/netutils
    commands:
      - 'curl -s --user api:$MAILGUN_APIKEY -XPOST https://api.mailgun.net/v3/$MAILGUN_DOMAIN/messages -F "from=Drone <postmaster@$MAILGUN_DOMAIN>" -F "to=$EMAIL_RECIPIENT" -F "subject=[$CI_REPO] WARNING: deployment failed" -F "text=Uh oh! The repo $CI_REPO just failed to deploy. Check out the build to see what went wrong: $DRONE_BUILD_LINK"'
    secrets:
      - email_recipient
      - mailgun_apikey
      - mailgun_domain
    when:
      branch: master
      event: [push, tag, deployment]
      status: failure
