Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "keithbartholomew-com-artifacts"
      OwnershipControls:
        Rules:
          - ObjectOwnership: "BucketOwnerEnforced"
