version: 2
jobs:
  pretest:
    docker:
      - image: cimg/node:14.15.4
    working_directory: ~/workspace
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run: scripts/build-frontend.sh
  publish_image:
    docker:
      - image: cimg/node:14.15.4
    working_directory: ~/workspace
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD quay.io
          docker build -t quay.io/ktbartholomew/keithbartholomew.com:$CIRCLE_SHA1 .
          docker push quay.io/ktbartholomew/keithbartholomew.com:$CIRCLE_SHA1
  update_deployment:
    docker:
      - image: gcr.io/google_containers/hyperkube:v1.13.5
    working_directory: ~/workspace
    steps:
      - checkout
      - run: scripts/update_deployment.sh

workflows:
  version: 2
  test:
    jobs:
      - pretest
      - publish_image:
          filters:
            branches:
              only: master
          requires:
            - pretest
      - update_deployment:
          requires:
            - publish_image
