version: 2
jobs:
  test:
    docker:
      - image: node:8.9.1
    working_directory: /workspace
    steps:
      - checkout
      - run: npm install
      - run: scripts/build-frontend.sh
workflows:
  version: 2
  test:
    jobs:
      - test
