version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8.9.1
    working_directory: ~/workspace
    steps:
      - checkout
      - run: npm install
      - run: scripts/build-frontend.sh
      - persist_to_workspace:
          root: ~/workspace
          paths:
            - dist
  push:
    docker:
      - image: circleci/node:8.9.1
    working_directory: ~/workspace
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: ~/workspace/dist
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD quay.io
      - run: ls -al
      - run: |
          "docker build -t quay.io/ktbartholomew/keithbartholomew.com:$CIRCLE_SHA1 ~/workspace"
workflows:
  version: 2
  test:
    jobs:
      - test
      - push:
          filters:
            branches:
              only: circleci
          requires:
            - test
