apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: keithbartholomew
  namespace: keithbartholomew
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: keithbartholomew
        role: frontend
      annotations:
        gitCommit: ${DRONE_COMMIT_SHA:-0}
    spec:
      containers:
        - name: keithbartholomew
          image: quay.io/ktbartholomew/os:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
