apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: os
  namespace: os
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: os
        role: frontend
      annotations:
        gitCommit: ${DRONE_COMMIT_SHA:-0}
    spec:
      containers:
        - name: os
          image: quay.io/ktbartholomew/os:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
