apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  namespace: keithbartholomew
  name: deployment-updater
rules:
- apiGroups: ["", "extensions"]
  resources: ["deployments"]
  verbs: ["get", "list", "update", "patch", "create"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: serviceaccount-deployment-updater
  namespace: keithbartholomew
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deployment-updater
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: system:serviceaccount:keithbartholomew:default
